import datetime,time
import os as os
from tkinter import StringVar, Text, Variable
#****************************************************************************************************************************************************************************************************************************************************************
# Variables Genericas                                                                                                                                                                                                                                           *
#****************************************************************************************************************************************************************************************************************************************************************
Dia=        datetime.datetime.today().day                                                                                           # Variable de Dia                                                                                                           *
Mes=        datetime.datetime.today().month                                                                                         # Variable de Mes                                                                                                           *
Hini=       datetime.datetime.now()                                                                                                 # Horario de inicio                                                                                                         *
Mensaje=    str()                                                                                                                   # Variable que utilizo para confeccionar los mensajes a mostrar en la aplicación                                            *
Dato=       str()                                                                                                                   # Variable para comparar el valor de planilla contra el ingresado en el buscador                                            *
Registro=   str()
Fondo='#5B5B5B'                                                                                                                     # Color Amarillo de Prosegur'#FFCC01'                                                                                   
Fuente=("Arial",12)                                                                                                                 # Estilo de Fuente a utilizar                                                                                               *
#****************************************************************************************************************************************************************************************************************************************************************
new_user=os.environ['USERPROFILE']                                                                                                  # Identifico el "UserProfile" de la pc para poder encontrar las carpetas instaladas en el Setup.py                          *
user=new_user.replace("\\","/")                                                                                                     # Reemplazo "\" por "/" dado a que no reconocen la ruta en Python                                                           *

path=open(user+'/Desktop/Soft/Path.txt')                                                                                            # Busco el archivo donde se encuentran las rutas preestablecidas para encontrar los archivos. (Las cuales se pueden         *
lineas=path.readlines()                                                                                                             # modificar en caso que asi se quiera)                                                                                      *

log=open(user  + (str(lineas[1])[:-1]),mode="a")                                                                                    # Ruta de Archivo donde se encuentran los Logs de eventos                                                                   *
#****************************************************************************************************************************************************************************************************************************************************************    
#ws= str()
reg_ws=str()
#****************************************************************************************************************************************************************************************************************************************************************
# Variables utilizadas en el buscador                                                                                                                                                                                                                           *
#****************************************************************************************************************************************************************************************************************************************************************
num=        int(1)                                                                                                                  # Variable para poder navegar por el listado Excel                                                                          *
limite=     3000                                                                                                                    # Limite de renglones para buscar                                                                                           *
Mensaje=    str()                                                                                                                   # Variable para poder mostrar mensaje                                                                                       *
#****************************************************************************************************************************************************************************************************************************************************************
Texto=str()                                                                                                                         # Variable para poder escribir e imprimir en pantalla o CMD                                                                 *
Sdia=int()                                                                                                                          # Variable para buscar "Día"                                                                                                *
Smes=int()                                                                                                                          # Variable para buscar "Mes"                                                                                                *
Step=int()                                                                                                                          # Variable para marcar el paso a ejecutar en el programa                                                                    *
Ftree='#444444'
#****************************************************************************************************************************************************************************************************************************************************************
var=int()                                                                                                                           # Variable de uso general para pruebas                                                                                      *
#****************************************************************************************************************************************************************************************************************************************************************
Renglon=30                                                                                                                          # Defino el valor a utilizar commo Renglones para poder las etiquetas sobre la ventana del soft                             *
Wtree=str()                                                                                                                         # Utilizo este Str para poder mover el dato del Tree a "Modificar.py" y poder modificar dentro de las otras Tablas          
#****************************************************************************************************************************************************************************************************************************************************************
S_t1="CCTV"                                                                                                                         # Colocamos el Nombre de la Tabla de archivo para poder visualizar dentro del Tree. Esta Tabla se Llama "CCTV"              *
S_t2="CA"                                                                                                                           # Tabla "CA"                                                                                                                *
S_t3="Lectoras"                                                                                                                     # Tabla "Lectoras"                                                                                                          *
S_t4="Avigilon"                                                                                                                     # Tabla "Avigilon"                                                                                                          *
#****************************************************************************************************************************************************************************************************************************************************************
# Variables utilizadas en el Modificador                                                                                                                                                                                                                           *
#****************************************************************************************************************************************************************************************************************************************************************
Servidor=str()
Comparador=int()                                                                                                                           # Variable de uso general para pruebas                                                                                      *
Dato=str()                                                                                                                          # Variable para poder obtener datos y poder comparar                                                                        *
Num=int(1)                                                                                                                          # Variable para poder navegar por el listado Excel                                                                          *
Limite=3000                                                                                                                         # Limite de renglones para buscar                                                                                           *
Posicion=150
Ancho=37
Bh=20
print (Wtree)